kind: pipeline
name: default

steps:
- name: build  
  image: plugins/docker
  settings:
    repo: cnrancher/global-monitoring-ui
    target: build
    dry_run: true
  when:
    event:
    - pull_request
- name: release  
  image: plugins/docker
  settings:
    repo: cnrancher/global-monitoring-ui
    auto_tag: true
    target: production
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    - tag